config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :bookings
  resources :tickets
  resources :urgencies
  devise_for :users
  resources :users
  resources :roles
  resources :resources

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get '/main' => 'static#index'

end

app/models/urgency.rb
class Urgency < ActiveRecord::Base
end

app/controllers/urgencies_controller.rb
class UrgenciesController < ApplicationController
  before_action :set_urgency, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, except: [:index]

  # GET /urgencies
  # GET /urgencies.json
  def index
    @urgencies = Urgency.all
  end

  # GET /urgencies/1
  # GET /urgencies/1.json
  def show
  end

  # GET /urgencies/new
  def new
    @urgency = Urgency.new
  end

  # GET /urgencies/1/edit
  def edit
  end

  # POST /urgencies
  # POST /urgencies.json
  def create
    @urgency = Urgency.new(urgency_params)

    respond_to do |format|
      if @urgency.save
        format.html { redirect_to @urgency, notice: 'Nivel de urgencia creado satisfactoriamente' }
        format.json { render :show, status: :created, location: @urgency }
      else
        format.html { render :new }
        format.json { render json: @urgency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urgencies/1
  # PATCH/PUT /urgencies/1.json
  def update
    respond_to do |format|
      if @urgency.update(urgency_params)
        format.html { redirect_to @urgency, notice: 'Nivel de urgencia actualizado satisfactoriamente' }
        format.json { render :show, status: :ok, location: @urgency }
      else
        format.html { render :edit }
        format.json { render json: @urgency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urgencies/1
  # DELETE /urgencies/1.json
  def destroy
    @urgency.destroy
    respond_to do |format|
      format.html { redirect_to urgencies_url, notice: 'Urgencia destruida' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_urgency
      @urgency = Urgency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def urgency_params
      params.require(:urgency).permit(:level)
    end
end

app/helpers/urgencies_helper.rb
module UrgenciesHelper
end

app/views/urgencies/_form.html.erb
<%= form_for(@urgency) do |f| %>
  <% if @urgency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@urgency.errors.count, "error") %> prohibited this urgency from being saved:</h2>

      <ul>
      <% @urgency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/urgencies/edit.html.erb
<h1>Editar urgencia</h1>

<hr/>

<%= render 'form' %>

<%= link_to 'Mostrar', @urgency %> |
<%= link_to 'Volver', urgencies_path %>

app/views/urgencies/index.html.erb
<h1>Urgencias</h1>

<%= link_to 'Nueva urgencia', new_urgency_path, class: 'btn' %>

<hr/>

<table class="listing small">
  <thead>
    <tr class="headers">
      <th>Nivel</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @urgencies.each do |urgency| %>
      <tr>
        <td><%= urgency.level %></td>
        <td><%= link_to 'Ver', urgency %></td>
        <td><%= link_to 'Editar', edit_urgency_path(urgency) %></td>
        <td><%= link_to 'Eliminar', urgency, method: :delete, data: { confirm: '¿Seguro que deseas eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/urgencies/new.html.erb
<h1>Nueva urgencia</h1>

<hr/>

<%= render 'form' %>

<%= link_to 'Volver', :back, class: 'btn without-plus' %>

app/views/urgencies/show.html.erb
<p>
  <strong>Level:</strong>
  <%= @urgency.level %>
</p>

<%= link_to 'Edit', edit_urgency_path(@urgency) %> |
<%= link_to 'Back', :back %>