config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :bookings
  resources :tickets
  resources :urgencies
  devise_for :users
  resources :users
  resources :roles
  resources :resources

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get '/main' => 'static#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :ticket
  has_one :urgency
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Tarea creada satisfactoriamente' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Tarea actualizada satisfactoriamente' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Tarea eliminada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:ticket_id, :description, :urgency_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticket %><br>
    <%= f.text_field :ticket %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_form_for_edit.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :urgency_id %>
    <%= f.select :urgency_id, options_for_select(Urgency.all.map{ |u| [u.level, u.id] }) %>
  </div>

  <div class="actions">
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editar tarea</h1>
<hr/>

<%= render 'form_for_edit' %>

<%= link_to 'Mostrar', @task %> |
<%= link_to 'Volver', :back %>

app/views/tasks/index.html.erb
<h1>Tareas</h1>
<hr/>

<table class="listing">
  <thead>
    <tr>
      <th>Incidencia</th>
      <th>Tarea</th>
      <th>Estado</th>
      <th colspan="2">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.ticket_id, ticket_path(Ticket.find(task.ticket_id).id) %></td>
        <td><%= task.description %></td>
        <td><%= Urgency.find(task.urgency_id).level %></td>
        <td><%= link_to 'Editar', edit_task_path(task) %></td>
        <td><%= link_to 'Eliminar', task, method: :delete, data: { confirm: '¿Seguro que deseas eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<h1>Tarea</h1>
<hr/>
<%= render 'form' %>

<%= link_to 'Volver', :back, class:'btn without-plus' %>

app/views/tasks/show.html.erb
<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>