config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :bookings
  resources :tickets
  resources :urgencies
  devise_for :users
  resources :users
  resources :roles
  resources :resources

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get '/main' => 'static#index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  has_one :urgency
  has_many :tasks, dependent: :destroy
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :description, :created_at, :user_id, :urgency_id)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id, :value => "#{current_user.name} #{current_user.surname}", disabled: true %>
  </div>
  <div class="field">
    <%= f.label :urgency %>
    <%= f.select :urgency_id, options_for_select(Urgency.all.map{ |u| [u.level, u.id] }) %>
  </div>
  <div class="actions">
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editar incidencia</h1>

<hr/>

<%= render 'form' %>

<%= link_to 'Mostrar', @ticket %> |
<%= link_to 'Volver', tickets_path %>

app/views/tickets/index.html.erb
<h1>Incidencias</h1>

<%= link_to 'Crear nueva incidencia', new_ticket_path, class: 'btn' %>

<hr/>

<table class="listing">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descripcion</th>
      <th>Creado a las</th>
      <th>Estado</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.title %></td>
        <td><%= ticket.description %></td>
        <td><%= ticket.created_at %></td>
        <td><%= Urgency.find(ticket.urgency_id).level %></td>
        <td><%= link_to 'Ver', ticket %></td>
        <td><%= link_to 'Editar', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Eliminar', ticket, method: :delete, data: { confirm: '¿Seguro que deseas eliminar?' } %></td>
        <% if current_user.is_user_admin? %>
          <td><%= link_to 'Generar tarea', new_task_path(ticket_id: ticket.id) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/new.html.erb
<h1>Nueva incidencia</h1>

<hr/>
  <%= render 'form' %>

  <%= link_to 'Volver', :back, class: 'btn without-plus' %>

app/views/tickets/show.html.erb
<div class="element">
  <div class="data">
    <p><strong>Titulo: </strong>
    <%= @ticket.title %></p>
  </div>

  <div class="data">
    <p><strong>Descripcion: </strong>
    <%= @ticket.description %></p>
  </div>

  <div class="data">
    <p><strong>Creado a las: </strong>
    <%= @ticket.created_at %></p>
  </div>

  <div class="data">
    <p><strong>Estado actual: </strong>
    <%= Urgency.find(@ticket.urgency_id).level %></p>
  </div>
</div>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', :back %>