config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :bookings
  resources :tickets
  resources :urgencies
  devise_for :users
  resources :users
  resources :roles
  resources :resources

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get '/main' => 'static#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :resource
  belongs_to :user

  validates_presence_of :start, :end
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :ticket
  has_one :urgency
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  has_one :urgency
  has_many :tasks, dependent: :destroy
end

app/models/urgency.rb
class Urgency < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  has_one :role
  has_many :bookings

  def is_user_admin?
    Role.find_by(id: self.role_id).role.eql? 'admin'
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, except: [:index]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Rol creado satisfactoriamente' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Rol actualizado satisfactoriamente' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Rol eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:role)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.last(3)
    @tickets = Ticket.last(3)
    @resources = Resource.last(3)
    @bookings = Booking.last(3)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Tarea creada satisfactoriamente' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Tarea actualizada satisfactoriamente' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Tarea eliminada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:ticket_id, :description, :urgency_id)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :description, :created_at, :user_id, :urgency_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, except: [:show]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuario creado satisfactoriamente' }
        format.json { render :index, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:id, :email, :name, :surname, :password, :role_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/urgencies_helper.rb
module UrgenciesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Narantic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="topbar">
    <% if user_signed_in? %>
      <div class="wrapper">
        <ul>
          <li><%= link_to 'Mi cuenta', user_path(current_user.id) %></li>
          <li><%= link_to 'Cerrar sesión', destroy_user_session_path, :method => :delete %></li>
        </ul>
      </div>
    <% end %>
  </div>
  <header>
    <div class="wrapper">
      <h1><%= link_to 'Narantic', main_path %></h1>
      <nav id="menu">
        <ul>
          <li><%= link_to 'Reservas', bookings_path %></li>
          <li><%= link_to 'Incidencias', tickets_path %></li>
          <% if user_signed_in? && current_user.is_user_admin? %>
            <li><%= link_to 'Tareas', tasks_path %></li>
            <li><%= link_to 'Recursos', resources_path %></li>
            <li><%= link_to 'Roles', roles_path %></li>
            <li><%= link_to 'Urgencias', urgencies_path %></li>
            <li><%= link_to 'Usuarios', users_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
  <div class="content">
    <div class="wrapper">
      <% flash.each do |name, message| %>
        <%= content_tag(:div, message, class: 'alert') %>
      <% end %>
      <%= yield %>
    </div>
  </div>
  <div class="footer">
    <div class="wrapper">
      <p>Narantic 2015</p>
    </div>
  </div>
</body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editar recurso</h1>

<hr/>

<%= render 'form' %>

<%= link_to 'Mostrar', @resource %> |
<%= link_to 'Volver', resources_path %>

app/views/resources/index.html.erb
<h1>Recursos</h1>

<%= link_to 'Nuevo recurso', new_resource_path, class: 'btn' %>

<hr/>

<table class="listing medium">
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= link_to 'Ver', resource %></td>
        <td><%= link_to 'Editar', edit_resource_path(resource) %></td>
        <td><%= link_to 'Eliminar', resource, method: :delete, data: { confirm: '¿Seguro que deseas eliminar??' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/resources/new.html.erb
<h1>Nuevo recurso</h1>

<hr/>

<%= render 'form' %>

<%= link_to 'Volver', :back, class: 'btn without-plus' %>

app/views/resources/show.html.erb
<div class="element">
  <div class="data">
    <p><strong>Nombre: </strong>
    <%= @resource.name %></p>
  </div>
</div>

<%= link_to 'Editar', edit_resource_path(@resource) %> |
<%= link_to 'Volver', :back %>